language: node_js
node_js: '6.4'
os: linux
env:
  - NODE_ENV=production
addons:
  ssh_known_hosts: 138.68.67.135
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install sshpass
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
script:
  - yarn run build
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then sshpass -e rsync -r --delete-after ./dist travis@138.68.67.135:/var/www/presentation.altwiener-markt.at/html/; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then sshpass -e rsync -r --delete-after ./index.html travis@138.68.67.135:/var/www/presentation.altwiener-markt.at/html/; fi
notifications:
  email:
    recipients: office@lukasholzer.com
    on_success: never
    on_failure: always
